INSERT INTO PERFUME (NAME, STOCK, PRICE, BRAND) VALUES ('Aqua Essence', 50, 29.99, 'Oceanic');
INSERT INTO PERFUME (NAME, STOCK, PRICE, BRAND) VALUES ('Midnight Bloom', 30, 49.90, 'Floraluxe');
INSERT INTO PERFUME (NAME, STOCK, PRICE, BRAND) VALUES ('Citrus Rush', 75, 19.50, 'Zestify');