spring:
  application:
    name: msvc-gateway
  config:
    import : 'optional:configserver:http://localhost:8888'

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: Perfume Service
        url: http://localhost:8090/v3/api-docs
      - name: Sale Service
        url: http://localhost:9090/v3/api-docs
      - name: User Service
        url: http://localhost:9080/v3/api-docs